// Mocks generated by Mockito 5.4.4 from annotations
// in sangeet/test/unit_test/favorite_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sangeet/core/failure/failure.dart' as _i6;
import 'package:sangeet/features/favorite/domain/entity/favorite_entity.dart'
    as _i7;
import 'package:sangeet/features/favorite/domain/repository/favorite_repository.dart'
    as _i2;
import 'package:sangeet/features/favorite/domain/usecases/favorite_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIFavoriteRepository_0 extends _i1.SmartFake
    implements _i2.IFavoriteRepository {
  _FakeIFavoriteRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteUseCase extends _i1.Mock implements _i4.FavoriteUseCase {
  @override
  _i2.IFavoriteRepository get favoriteRepository => (super.noSuchMethod(
        Invocation.getter(#favoriteRepository),
        returnValue: _FakeIFavoriteRepository_0(
          this,
          Invocation.getter(#favoriteRepository),
        ),
        returnValueForMissingStub: _FakeIFavoriteRepository_0(
          this,
          Invocation.getter(#favoriteRepository),
        ),
      ) as _i2.IFavoriteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.FavoriteEntity>>> getAllFavorites(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFavorites,
          [page],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.FavoriteEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.FavoriteEntity>>(
          this,
          Invocation.method(
            #getAllFavorites,
            [page],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.FavoriteEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.FavoriteEntity>>(
          this,
          Invocation.method(
            #getAllFavorites,
            [page],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.FavoriteEntity>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.FavoriteEntity>> getFavorite(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorite,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.FavoriteEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.FavoriteEntity>(
          this,
          Invocation.method(
            #getFavorite,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.FavoriteEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.FavoriteEntity>(
          this,
          Invocation.method(
            #getFavorite,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.FavoriteEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> addSongToFavorite(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSongToFavorite,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addSongToFavorite,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
                _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addSongToFavorite,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> removeSongFromFavorite(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeSongFromFavorite,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #removeSongFromFavorite,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
                _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #removeSongFromFavorite,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}
