// Mocks generated by Mockito 5.4.4 from annotations
// in sangeet/test/unit_test/playlist_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sangeet/core/failure/failure.dart' as _i6;
import 'package:sangeet/features/playlist/domain/entity/playlist_entity.dart'
    as _i7;
import 'package:sangeet/features/playlist/domain/repository/playlist_repository.dart'
    as _i2;
import 'package:sangeet/features/playlist/domain/usecases/playlist_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIPlaylistRepository_0 extends _i1.SmartFake
    implements _i2.IPlaylistRepository {
  _FakeIPlaylistRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlaylistUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistUseCase extends _i1.Mock implements _i4.PlaylistUseCase {
  @override
  _i2.IPlaylistRepository get playlistRepository => (super.noSuchMethod(
        Invocation.getter(#playlistRepository),
        returnValue: _FakeIPlaylistRepository_0(
          this,
          Invocation.getter(#playlistRepository),
        ),
        returnValueForMissingStub: _FakeIPlaylistRepository_0(
          this,
          Invocation.getter(#playlistRepository),
        ),
      ) as _i2.IPlaylistRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.PlaylistEntity>>> getAllPlaylists(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPlaylists,
          [page],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.PlaylistEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.PlaylistEntity>>(
          this,
          Invocation.method(
            #getAllPlaylists,
            [page],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.PlaylistEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.PlaylistEntity>>(
          this,
          Invocation.method(
            #getAllPlaylists,
            [page],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.PlaylistEntity>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.PlaylistEntity>> getPlaylist(
          String? playlistId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaylist,
          [playlistId],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.PlaylistEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.PlaylistEntity>(
          this,
          Invocation.method(
            #getPlaylist,
            [playlistId],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.PlaylistEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.PlaylistEntity>(
          this,
          Invocation.method(
            #getPlaylist,
            [playlistId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.PlaylistEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> addSongToPlaylist(
    String? playlistId,
    String? songId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSongToPlaylist,
          [
            playlistId,
            songId,
          ],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addSongToPlaylist,
            [
              playlistId,
              songId,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
                _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addSongToPlaylist,
            [
              playlistId,
              songId,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> addPlaylist(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPlaylist,
          [name],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addPlaylist,
            [name],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
                _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addPlaylist,
            [name],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> updatePlaylist(
    String? playlistId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlaylist,
          [
            playlistId,
            name,
          ],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #updatePlaylist,
            [
              playlistId,
              name,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
                _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #updatePlaylist,
            [
              playlistId,
              name,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> deletePlaylist(
          String? playlistId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePlaylist,
          [playlistId],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #deletePlaylist,
            [playlistId],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
                _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #deletePlaylist,
            [playlistId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}
